name: tictacgame
description: "A new Flutter project."
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  upgrader: ^8.1.0
  google_fonts: ^5.1.0
  url_launcher: ^6.1.11
  audioplayers: ^5.0.0
  lottie: ^2.4.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/mouse-click-153941.mp3
